spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio_manager
    username: postgres
    password: newton123
    driver-class-name: org.postgresql.Driver
  messages:
    basename: messages
    encoding: utf-8
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

